### ISSUE TITLE
bug: 405 returned while registering on deployed website

### ISSUE THREAD

**Issue by HeroicHitesh** [anitab-org/stem-diverse-tv-cms#43] opened 2021-03-10 03:33 UTC
### Describe the bug
Status Code 405 is returned while registering as a new user on deployed website

### To Reproduce
1. Go to [`https://anitab-org.github.io/stem-diverse-tv-cms`](https://anitab-org.github.io/stem-diverse-tv-cms)
2. Click on the `Register` button at the top
2. Fill in all the details
3. Click on `Register`
4. See the status code in the network tab of the inspector, it will show 405

### Expected behavior
Registration should happen successfully and status code 200 should be returned

### Screenshots
<img width="1440" alt="Screenshot 2021-03-10 at 9 00 25 AM" src="https://user-images.githubusercontent.com/37622734/110572253-16e70280-817f-11eb-8243-682699e485bf.png">

### Desktop (please complete the following information):
 - OS: MacOS
 - Browser: Chrome, Safari
 - Version: 88.0.4324.192 (Official Build) (x86_64), 14.0.3 (16610.4.3.1.4)

### Additional Context 
Issue created as per this [conversation](https://anitab-org.zulipchat.com/#narrow/stream/225705-STEM-diverse-tv/topic/Issue.20requests/near/229357485) on Zulip

**Comment by chinmaym07** [comment] 2021-03-10 07:10
@HeroicHitesh I think this issue is when you try to register on the hosted app & an issue #29 is already opened for this & a PR #40 is approved & will fix that ...Thankyou .. 👍🏻  😁

**Comment by HeroicHitesh** [comment] 2021-03-10 07:18
> @HeroicHitesh I think this issue is when you try to register on the hosted app & an issue #29 is already opened for this & a PR #40 is approved & will fix that ...Thankyou .. 👍🏻 😁

@annabauza Your thoughts? Should I close this issue?

**Comment by Rahulm2310** [comment] 2021-03-21 20:12
@HeroicHitesh I think this is duplicate of #29. You can close it.

**Comment by HeroicHitesh** [comment] 2021-03-22 01:37
Sure @Rahulm2310 
@annabauza Closing this now as PR #47 already exists solving #29

**Closed** 2021-03-22 01:38 UTC
